/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.trabalhoFinalSA;

/**
 *
 * @author Aluno
 */
public class trabalhoFinalFrame extends javax.swing.JFrame {

    /**
     * Creates new form trabalhoFinal
     */
    public trabalhoFinalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        BarraMenu = new javax.swing.JMenuBar();
        menuManterColaborador = new javax.swing.JMenu();
        menuCadastrarColaborador = new javax.swing.JMenuItem();
        menuEditarColaborador = new javax.swing.JMenuItem();
        menuEliminarColaborador = new javax.swing.JMenuItem();
        menuListarColaborador = new javax.swing.JMenuItem();
        menuManterEquipe = new javax.swing.JMenu();
        menuCadastrarEquipe = new javax.swing.JMenuItem();
        menuEditarEquipe = new javax.swing.JMenuItem();
        menuEliminarEquipe = new javax.swing.JMenuItem();
        menuListarEquipe = new javax.swing.JMenuItem();
        menuConsultarAgenda = new javax.swing.JMenu();
        menuManterAgenda = new javax.swing.JMenu();
        menuAdicionarTarefa = new javax.swing.JMenuItem();
        menuEliminarTarefa = new javax.swing.JMenuItem();
        menuEditarTarefa = new javax.swing.JMenuItem();
        menuVerAgenda = new javax.swing.JMenu();
        menuAgendaColaborador = new javax.swing.JMenuItem();
        menuAgendaEquipe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuManterColaborador.setText("Colaborador");

        menuCadastrarColaborador.setText("Cadastrar ");
        menuCadastrarColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarColaboradorActionPerformed(evt);
            }
        });
        menuManterColaborador.add(menuCadastrarColaborador);

        menuEditarColaborador.setText("Editar ");
        menuEditarColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarColaboradorActionPerformed(evt);
            }
        });
        menuManterColaborador.add(menuEditarColaborador);

        menuEliminarColaborador.setText("Eliminar ");
        menuManterColaborador.add(menuEliminarColaborador);

        menuListarColaborador.setText("Listar ");
        menuListarColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarColaboradorActionPerformed(evt);
            }
        });
        menuManterColaborador.add(menuListarColaborador);

        BarraMenu.add(menuManterColaborador);

        menuManterEquipe.setText("Equipe");

        menuCadastrarEquipe.setText("Cadastrar");
        menuManterEquipe.add(menuCadastrarEquipe);

        menuEditarEquipe.setText("Editar");
        menuEditarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarEquipeActionPerformed(evt);
            }
        });
        menuManterEquipe.add(menuEditarEquipe);

        menuEliminarEquipe.setText("Eliminar");
        menuManterEquipe.add(menuEliminarEquipe);

        menuListarEquipe.setText("Listar");
        menuManterEquipe.add(menuListarEquipe);

        BarraMenu.add(menuManterEquipe);

        menuConsultarAgenda.setText("Consultar Agênda");

        menuManterAgenda.setText("Manter Tarefas");

        menuAdicionarTarefa.setText("Adicionar Tarefa");
        menuManterAgenda.add(menuAdicionarTarefa);

        menuEliminarTarefa.setText("Eliminar Tarefa");
        menuManterAgenda.add(menuEliminarTarefa);

        menuEditarTarefa.setText("Editar Tarefa");
        menuManterAgenda.add(menuEditarTarefa);

        menuConsultarAgenda.add(menuManterAgenda);

        menuVerAgenda.setText("Ver Agênda");

        menuAgendaColaborador.setText("Agenda do Colaborador");
        menuVerAgenda.add(menuAgendaColaborador);

        menuAgendaEquipe.setText("Agenda da Equipe");
        menuAgendaEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgendaEquipeActionPerformed(evt);
            }
        });
        menuVerAgenda.add(menuAgendaEquipe);

        menuConsultarAgenda.add(menuVerAgenda);

        BarraMenu.add(menuConsultarAgenda);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastrarColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarColaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastrarColaboradorActionPerformed

    private void menuAgendaEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgendaEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAgendaEquipeActionPerformed

    private void menuEditarColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarColaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEditarColaboradorActionPerformed

    private void menuListarColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarColaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuListarColaboradorActionPerformed

    private void menuEditarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEditarEquipeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trabalhoFinalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trabalhoFinalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trabalhoFinalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trabalhoFinalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trabalhoFinalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem menuAdicionarTarefa;
    private javax.swing.JMenuItem menuAgendaColaborador;
    private javax.swing.JMenuItem menuAgendaEquipe;
    private javax.swing.JMenuItem menuCadastrarColaborador;
    private javax.swing.JMenuItem menuCadastrarEquipe;
    private javax.swing.JMenu menuConsultarAgenda;
    private javax.swing.JMenuItem menuEditarColaborador;
    private javax.swing.JMenuItem menuEditarEquipe;
    private javax.swing.JMenuItem menuEditarTarefa;
    private javax.swing.JMenuItem menuEliminarColaborador;
    private javax.swing.JMenuItem menuEliminarEquipe;
    private javax.swing.JMenuItem menuEliminarTarefa;
    private javax.swing.JMenuItem menuListarColaborador;
    private javax.swing.JMenuItem menuListarEquipe;
    private javax.swing.JMenu menuManterAgenda;
    private javax.swing.JMenu menuManterColaborador;
    private javax.swing.JMenu menuManterEquipe;
    private javax.swing.JMenu menuVerAgenda;
    // End of variables declaration//GEN-END:variables
}
