/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.trabalhoFinalSA.views;

import br.senai.sc.trabalhoFinalSA.dao.AgendaDao;
import br.senai.sc.trabalhoFinalSA.dao.AgendaEquipeDao;
import br.senai.sc.trabalhoFinalSA.modelo.Agenda;
import br.senai.sc.trabalhoFinalSA.modelo.Colaborador;
import br.senai.sc.trabalhoFinalSA.modelo.Equipe;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vilmarpavesijunior
 */

public class ListagemAgendaEquipe extends javax.swing.JPanel {
 

 private CardLayout cl;
 private int codAgeEqu;
 private String criAge, comAge, titAge, desAge;
    
    public ListagemAgendaEquipe() {
        initComponents();
       
        this.add(painelListagemAgenda, "painelListagemAgenda");
        this.add(painelEdicao, "painelEdicao");
        
        this.cl  = (CardLayout) this.getLayout();
        cl.show(this, "painelListagemAgenda");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelListagemAgenda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListagemAgenda = new javax.swing.JTable();
        painelEdicao = new javax.swing.JPanel();
        LabelTituloCadastroDeTarefa = new javax.swing.JLabel();
        LabelDataDeCriacao = new javax.swing.JLabel();
        LabelDataDeFinalizacao = new javax.swing.JLabel();
        cpDataCriacao = new javax.swing.JFormattedTextField();
        cpDataFinalizacao = new javax.swing.JFormattedTextField();
        LabelTituloTarefa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cpDescricaoTarefa = new javax.swing.JTextArea();
        cpTituloTarefa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        tblListagemAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data de Criação", "Data de Entrega", "Título", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListagemAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListagemAgendaMouseClicked(evt);
            }
        });
        tblListagemAgenda.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblListagemAgendaComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tblListagemAgenda);

        javax.swing.GroupLayout painelListagemAgendaLayout = new javax.swing.GroupLayout(painelListagemAgenda);
        painelListagemAgenda.setLayout(painelListagemAgendaLayout);
        painelListagemAgendaLayout.setHorizontalGroup(
            painelListagemAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        painelListagemAgendaLayout.setVerticalGroup(
            painelListagemAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );

        add(painelListagemAgenda, "card2");

        LabelTituloCadastroDeTarefa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelTituloCadastroDeTarefa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTituloCadastroDeTarefa.setText("Edição de Tarefa");

        LabelDataDeCriacao.setText("Data de Início:");

        LabelDataDeFinalizacao.setText("Data de Entrega:");

        try {
            cpDataCriacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("      ##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            cpDataFinalizacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("       ##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        LabelTituloTarefa.setText("Título:");

        jLabel2.setText("Descrição:");

        cpDescricaoTarefa.setColumns(20);
        cpDescricaoTarefa.setRows(5);
        jScrollPane2.setViewportView(cpDescricaoTarefa);

        jLabel3.setText("(Max:50");

        jLabel4.setText("caracteres)");

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelEdicaoLayout = new javax.swing.GroupLayout(painelEdicao);
        painelEdicao.setLayout(painelEdicaoLayout);
        painelEdicaoLayout.setHorizontalGroup(
            painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelTituloCadastroDeTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelEdicaoLayout.createSequentialGroup()
                .addGroup(painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEdicaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelEdicaoLayout.createSequentialGroup()
                                .addComponent(LabelTituloTarefa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cpTituloTarefa))
                            .addGroup(painelEdicaoLayout.createSequentialGroup()
                                .addGroup(painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelEdicaoLayout.createSequentialGroup()
                                        .addComponent(LabelDataDeCriacao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cpDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painelEdicaoLayout.createSequentialGroup()
                                        .addComponent(LabelDataDeFinalizacao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cpDataFinalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(painelEdicaoLayout.createSequentialGroup()
                        .addGroup(painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelEdicaoLayout.createSequentialGroup()
                                .addGroup(painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEdicaoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(painelEdicaoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnEditar)
                                .addGap(53, 53, 53)
                                .addComponent(btnVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExcluir)
                                .addGap(26, 26, 26)))))
                .addContainerGap())
        );
        painelEdicaoLayout.setVerticalGroup(
            painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEdicaoLayout.createSequentialGroup()
                .addComponent(LabelTituloCadastroDeTarefa)
                .addGap(24, 24, 24)
                .addGroup(painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDataDeCriacao)
                    .addComponent(cpDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDataDeFinalizacao)
                    .addComponent(cpDataFinalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTituloTarefa)
                    .addComponent(cpTituloTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEdicaoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar)
                    .addComponent(btnVoltar)
                    .addComponent(btnExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(painelEdicao, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void tblListagemAgendaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblListagemAgendaComponentShown
        this.popularTabela();
    }//GEN-LAST:event_tblListagemAgendaComponentShown

        private void preencherFormulario(int codEqu){
        AgendaEquipeDao ageE = new AgendaEquipeDao();
        Equipe equ = new Equipe();
        codEqu = equ.getCodEqu();
        
        try {
            Agenda agenda = ageE.getAgendaEquipe(codEqu);
            cpDataCriacao.setText(agenda.getCriAge());
            cpDataFinalizacao.setText(agenda.getComAge());
            cpTituloTarefa.setText(agenda.getTitAge());
            cpDescricaoTarefa.setText(agenda.getDesAge());
         
           
           
        } catch (SQLException ex) {
            Logger.getLogger(ListagemAgendaEquipe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.codAgeEqu = codEqu;
    }
    
    
    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        Agenda age = new Agenda();
        Equipe equ = new Equipe();
        age.setCriAge(cpDataCriacao.getText());
        age.setComAge(cpDataFinalizacao.getText());
        age.setTitAge(cpTituloTarefa.getText());
        age.setDesAge(cpDescricaoTarefa.getText());
        equ.setCodEqu(this.codAgeEqu);

        AgendaEquipeDao ageEDao = new AgendaEquipeDao();
        try {
            ageEDao.alterar(age, equ);
            JOptionPane.showMessageDialog(null,"Tarefa da Equipe Atualizada com Sucesso!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Falha ao Atualizar a Tarefa da Equipe");
            Logger.getLogger(ListagemAgendaEquipe.class.getName()).log(Level.SEVERE,
                null, ex);

        }
        this.cl  = (CardLayout) this.getLayout();
        cl.show(this, "painelListagemAgenda");
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tblListagemAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListagemAgendaMouseClicked
         int linha = tblListagemAgenda.getSelectedRow();
        
        if (linha!= -1) {
            String codigo = tblListagemAgenda.getValueAt(linha, 0).toString();
            int codigoCliente = Integer.parseInt(codigo);
            this.preencherFormulario(codigoCliente);
            this.limparTabela();
            this.cl.show(this,"painelEdicao" );
        }
      
       
    }//GEN-LAST:event_tblListagemAgendaMouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
           this.cl  = (CardLayout) this.getLayout();
           cl.show(this, "painelListagem");
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Object[] options = {"Sim", "Não"};
        int opcaoSelecionada = JOptionPane.showOptionDialog(null, "Deseja realmente eliminar esta Tarefa ?", "Atenção!", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
     
        if (opcaoSelecionada ==0){
            AgendaEquipeDao ageEDao = new AgendaEquipeDao();
             try {
                 ageEDao.eliminar(this.criAge,this.comAge, this.titAge, this.desAge, this.codAgeEqu);
                 this.limparTabela(); 
                 this.cl.show(this,"painelListagemAgenda");
             } catch (SQLException ex) {
                 Logger.getLogger(ListagemAgendaEquipe.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
private void popularTabela () {
        AgendaEquipeDao ageE = new AgendaEquipeDao ();
        List<Agenda> listaAgenda;
        try {
            listaAgenda= ageE.listarAgenda();
            
        DefaultTableModel model = (DefaultTableModel) tblListagemAgenda.getModel();
        List<Object> lista = new ArrayList<Object> ();
        
        for(int i =0 ; i < listaAgenda.size(); i++) {
             Agenda a = listaAgenda.get(i);
             lista.add(new Object[]{a.getCriAge(), a.getComAge(),
                 a.getTitAge(),a.getDesAge()});
    }
        
        for(int idx = 0; idx < lista.size(); idx++) {
            model.addRow((Object []) lista.get(idx));
        }
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Obter as Tarefas do Banco de Dados!");
            Logger.getLogger(ListagemEquipe.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }

   private void limparTabela() {

        ((DefaultTableModel) tblListagemAgenda.getModel()).setNumRows(0);

        tblListagemAgenda.updateUI();
}
    




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDataDeCriacao;
    private javax.swing.JLabel LabelDataDeFinalizacao;
    private javax.swing.JLabel LabelTituloCadastroDeTarefa;
    private javax.swing.JLabel LabelTituloTarefa;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JFormattedTextField cpDataCriacao;
    private javax.swing.JFormattedTextField cpDataFinalizacao;
    private javax.swing.JTextArea cpDescricaoTarefa;
    private javax.swing.JTextField cpTituloTarefa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel painelEdicao;
    private javax.swing.JPanel painelListagemAgenda;
    private javax.swing.JTable tblListagemAgenda;
    // End of variables declaration//GEN-END:variables
}
