/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.trabalhoFinalSA.views;

import br.senai.sc.trabalhoFinalSA.dao.EquipeDao;
import br.senai.sc.trabalhoFinalSA.modelo.Equipe;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class ListagemEquipe extends javax.swing.JPanel {

    /**
     * Creates new form ListagemEquipe
     */
    private CardLayout cl;
    private int codEqu;
    public ListagemEquipe() {
        initComponents();
        
        this.add(painelListagemEquipe, "painelListagemEquipe");
        
        this.cl  = (CardLayout) this.getLayout();
        cl.show(this, "painelListagemEquipe");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        painelListagemEquipe = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListagemEquipe = new javax.swing.JTable();
        painelEdicaoEquipe = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        painelListagemEquipe.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                painelListagemEquipeComponentShown(evt);
            }
        });

        tblListagemEquipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Descrição"
            }
        ));
        jScrollPane1.setViewportView(tblListagemEquipe);

        javax.swing.GroupLayout painelListagemEquipeLayout = new javax.swing.GroupLayout(painelListagemEquipe);
        painelListagemEquipe.setLayout(painelListagemEquipeLayout);
        painelListagemEquipeLayout.setHorizontalGroup(
            painelListagemEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        painelListagemEquipeLayout.setVerticalGroup(
            painelListagemEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        add(painelListagemEquipe, "card3");

        javax.swing.GroupLayout painelEdicaoEquipeLayout = new javax.swing.GroupLayout(painelEdicaoEquipe);
        painelEdicaoEquipe.setLayout(painelEdicaoEquipeLayout);
        painelEdicaoEquipeLayout.setHorizontalGroup(
            painelEdicaoEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        painelEdicaoEquipeLayout.setVerticalGroup(
            painelEdicaoEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(painelEdicaoEquipe, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void popularTabela () {
         EquipeDao eq = new EquipeDao ();
        List<Equipe> listaEquipe;
        try {
            listaEquipe = eq.listarEquipes();
            
        DefaultTableModel model = (DefaultTableModel) tblListagemEquipe.getModel();
        List<Object> lista = new ArrayList<Object> ();
        
        for(int i =0 ; i < listaEquipe.size(); i++) {
             Equipe c = listaEquipe.get(i);
             lista.add(new Object[]{c.getNomEqu(), c.getDesEqu()});
    }
        
        for(int idx = 0; idx < lista.size(); idx++) {
            model.addRow((Object []) lista.get(idx));
        }
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Obter os Colaboradores do Banco de Dados!");
            Logger.getLogger(ListagemEquipe.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }
    
    private void painelListagemEquipeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_painelListagemEquipeComponentShown
      this.popularTabela();                               
    }//GEN-LAST:event_painelListagemEquipeComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelEdicaoEquipe;
    private javax.swing.JPanel painelListagemEquipe;
    private javax.swing.JTable tblListagemEquipe;
    // End of variables declaration//GEN-END:variables
}
