/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.trabalhoFinalSA.views;

import br.senai.sc.trabalhoFinalSA.dao.ColaboradorDao;
import br.senai.sc.trabalhoFinalSA.modelo.Colaborador;
import br.senai.sc.trabalhoFinalSA.trabalhoFinalFrame;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class PainelAlterarSenha extends javax.swing.JPanel {

    private Colaborador colaborador;

    public PainelAlterarSenha() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAlterarSenha = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelNovaSenha = new javax.swing.JLabel();
        labelConfirmarSenha = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        campoNovaSenha = new javax.swing.JPasswordField();
        campoConfirmaNovaSenha = new javax.swing.JPasswordField();
        btnSalvar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        labelAlterarSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelAlterarSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAlterarSenha.setText("Alterar senha");

        labelUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelUsuario.setText("Usuario");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Senha");

        labelNovaSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNovaSenha.setText("Nova senha");

        labelConfirmarSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelConfirmarSenha.setText("Confirme nova senha");

        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });

        campoConfirmaNovaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoConfirmaNovaSenhaActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalvar.setText("Salvar ");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUsuario)
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(campoSenha)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNovaSenha)
                        .addGap(18, 18, 18)
                        .addComponent(campoNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelConfirmarSenha)
                        .addGap(18, 18, 18)
                        .addComponent(campoConfirmaNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addComponent(labelAlterarSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(labelAlterarSenha)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario)
                    .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNovaSenha)
                    .addComponent(campoNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConfirmarSenha)
                    .addComponent(campoConfirmaNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnSalvar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void campoConfirmaNovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoConfirmaNovaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoConfirmaNovaSenhaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        ColaboradorDao cl = new ColaboradorDao();
        ColaboradorDao cl2 = new ColaboradorDao();
        char[] senha = campoNovaSenha.getPassword();
        char[] cosenha = campoConfirmaNovaSenha.getPassword();
        char[] senhaAt=campoSenha.getPassword();
        String novaSenha = "";
        String coNovaSenha = "";
        String senhaAtual="";
        
        for (int i = 0; i < senhaAt.length; i++) {
            senhaAtual+=senhaAt[i];
        }
        
        Colaborador c = null;
        try {
            c = cl.checar(campoUsuario.getText(), senhaAtual);
            this.colaborador = c;
            if (c == null) {
                JOptionPane.showMessageDialog(null, "Usuario ou senha incorretos");
                campoUsuario.setText(null);
                campoSenha.setText(null);
                campoConfirmaNovaSenha.setText(null);
                campoNovaSenha.setText(null);
            } else {
                for (int i = 0; i < cosenha.length; i++) {
                    coNovaSenha += cosenha[i];    
                }
                for (int i2 = 0; i2 < senha.length; i2++) {
                    novaSenha += senha[i2];
                }

                if (novaSenha.equals(coNovaSenha)) {
                    cl2.alterarSenha(c.getCodCol(), novaSenha);
                    JOptionPane.showMessageDialog(null, "nova senha salva");
                    campoUsuario.setText(null);
                    campoSenha.setText(null);
                    campoConfirmaNovaSenha.setText(null);
                    campoNovaSenha.setText(null);
                } else {
                    JOptionPane.showMessageDialog(null, "Confirmacao de nova senha incoreta");
                    campoConfirmaNovaSenha.setText(null);
                    campoNovaSenha.setText(null);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(trabalhoFinalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPasswordField campoConfirmaNovaSenha;
    private javax.swing.JPasswordField campoNovaSenha;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelAlterarSenha;
    private javax.swing.JLabel labelConfirmarSenha;
    private javax.swing.JLabel labelNovaSenha;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables
}
